#-------------------------------
# Site Settings

title: Alexia Buclet 🐝
logo: # You can add own logo. For example '/images/logo.png'.
description: Senior UX / Product Manager & DesignOps Freelance For Good
meta_description: "UX Designer et Product Manager freelance, j’accompagne les startups à impact pour concevoir des produits et services utiles, durables et adoptés naturellement."
meta_title: "UX / PM freelance pour startups à impact - Alexia Buclet"

menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    # - title: 'Offre'
    #   url: '/#offre'
    #- title: 'Experience'
    #  url: '/projects/'
    - title: 'Expériences'
      url: '/experiences/'
    - title: 'Speaker'
      url: '/speaker/'
    - title: 'Qui suis-je ?'
      url: '/about/'
    #- title: 'Pages'
    #  submenu:
    #  - url: '/about'
    #    title: 'About'
    #  - url: '/elements'
    #    title: 'Elements'

# Call to action button
cta__button__text: Contact

# Add global cover image (This field adds a background to the top and bottom of the site.)
#cover__image: '/images/378.jpg'


#-------------------------------
# Author Settings

author:
  name: Alexia Buclet
  title: Alexia Buclet
  bio: Senior UX Designer / Product Manager <br>Freelance For Good pour Produits / Services à Impact 🌍
  image: '/images/alexia-buclet.jpg'
  image_alt: "Photo d'Alexia Buclet"
  avatar: '/images/avatar.jpg'
  button__text: TO DEFINE
  # button in HTML

#-------------------------------
# Témoignages

testimonials:
  testimonial__title: "Ils m'ont fait confiance"
  testimonials_items:
    - name: 
      #designation: 
      content: "Le taff effectué pendant la mission a été top, bluffant et hyper utile !"
      #image: 
    - name: 
      #designation: 
      content: "Son expertise et sa capacité à piloter des projets complexes ont été impressionnants. C'est un réel plaisir de travailler en sa présence, elle apporte beaucoup d'énergie où qu'elle aille."
      #image: 
    - name: 
      #designation: 
      content: "Le rapport gain / prix vaut vraiment le coup niveau volume et impact pour l'app !"
      #image: 
    - name: 
      #designation: 
      content: "Alexia a systématiquement su adapter sa méthode et ses équipes dans un univers technologique et stratégie évoluant très rapidement, tout en conservant un niveau d'exigence élevé."
      #image: 
    - name: 
      #designation: 
      content: "Alexia est une personne à l'écoute, organisée et très dynamique, toujours avec une énergie positive et une bonne humeur communicative."
      #image:
    - name: 
      #designation: 
      content: "Son professionnalisme et son engagement font d'elle une collaboratrice précieuse avec qui il est un vrai plaisir de travailler."
      #image:



#-------------------------------
# Author resume

author_info:
  resume_title: "<span class=\"text-span\">Résumé</span>"
  accueil: "👋 Tu donnes tout pour créer une solution innovante et vertueuse, mais les utilisateur.ices ne sont pas au rendez-vous, les priorités s'accumulent et/ou les équipes sont perdues. Tu es au bon endroit !"
  benefits: "Ce que je peux t’apporter :<br/>✅ Une <strong>expérience utilisateur</strong> fluide et engageante, pour que ton produit / service devienne une évidence.<br/>✅ Une <strong>stratégie produit</strong> et une <strong>roadmap</strong> basées sur la réalité, pour répondre vraiment aux besoins clients.<br/>✅ Des <strong>process de travail</strong> plus efficaces, pour une équipe épanouie et productive.<br/>Avec du concret, du pragmatique et des solutions adaptées à tes ressources, loin des théories déconnectées du terrain."
  objective: "<strong>Objectif :</strong> concevoir en harmonie des produits / services que les gens adoptent durablement et recommandent avec enthousiasme !"
  profile: "<strong>Profil :</strong> Psychologue cognitiviste avec 15 ans d'expérience dans la tech, Certifiée \"écoconception de service numérique\" et formée à l'IA frugale 🌿"
  services: "<strong>Accompagnement :</strong> UX Design, Product Management et DesignOps."
  product_type: "<strong>Type de produits / services :</strong> numérique (ex : apps, logiciels, plateformes) et physique (ex : domotique, robotique) | B2B / B2C | innovation, IA frugale, gamification, immersion, deeptech, maps."
  mission_duration: "<strong>Durée de missions :</strong> d'une demi-journée à plusieurs semaines / mois (en plein temps ou partiel)."
  companies: "<strong>Structures :</strong> startups / entreprises innovantes à impact environnemental ou social avec des équipes pluridisciplinaires."
  languages: "<strong>Langues :</strong> français / anglais."
  area: "<strong>Zone géographique :</strong> région de Paris, distanciel et déplacements ponctuels."
  gift: "🎁 Pour confirmer ton envie de me faire confiance, commençons par un <strong>mini-audit gratuit ou discussion d'1h</strong> sur l'une de tes problématiques du moment."
  # calltoaction: "🤩 Travaillons ensemble !"

#-------------------------------
# Author clients


#-------------------------------
# Author pitch

#author_quiz:
  #description: "Si toi aussi tu aimes jouer, tu peux en apprendre plus grâce à ce <strong><a href='https://team-planet.com/fr' style='text-decoration: underline;' target='_blank'>quiz</a> </strong> et tenter de gagner une réduc 😁"


#-------------------------------
# Author pitch

author_pitch:
  statements:
    - description: 🧠 Psychologue cognitiviste de formation, l'humain est au coeur de mon expertise.

    - description: 💪 J'accompagne les startups/entreprises innovantes et impactantes qui ne peuvent pas avoir d'UX Designer à plein temps, ou qui ont besoin d'un regard extérieur. 

    - description: 🌿 Certifiée "écoconception de service numérique", je prends en compte les problématiques environnementale dans mes recommandations. 

    - description: "🕊 Je vise l'harmonie : que ce soit entre vos utilisateurs et votre produit, ou entre les membres de vos équipes."

    - description: 🤩 Travaillons ensemble ! 


#--------------------------------
# Section with 3 Columns Valeurs
columns_section:
  bigtitle: Mes <span class="text-span">valeurs</span> pour être utile et pertinente
  column:
   - title: "Adaptation"
     description: "Je m'adapte à votre réalité : produit, cible, délais, ressources, etc."
     image: "🦎"
     image_alt: "Icône d'un caméléon"

   - title: "Efficacité"
     description: "Je vise la frugalité en trouvant des moyens et des solutions simples et efficaces."
     image: "🦫"
     image_alt: "Icône d'un castor"

   - title: "Confiance"
     description: "J'aime accompagner les mêmes équipes dans une relation positive et de confiance."
     image: "🐝"
     image_alt: "Icône d'une abeille"


#-------------------------------
# Interventions

interventions:
  title: "Domaines d'<span class=\"text-span\">intervention</span>"
  items:
   - subtitle: "UX / Product Design"
     description: "L'expérience doit être positive avec des interactions intuitives, efficaces, efficientes et satisfaisantes, à toutes les étapes du parcours produit."
     items:
       - "<strong>😌 Pour les prévoyant.e.s :</strong> en amont du développement pour adopter la bonne stratégie pour les utilisateurs.rices."
       - "<strong>🤠 Pour les pressé.e.s :</strong> audit et recommandations sur l'expérience de votre produit."
       - "<strong>🫠 Pour les submergé.e.s :</strong> identifier avec du recul ce qui a vraiment de la valeur pour l'expérience de votre produit."
       - "<strong>👯 Pour du renfort :</strong> UX Design complet d'une feature ou d'un produit (analyse des besoins, benchmark, user journey, wireframes, prototypes Figma, spécifications, suivi d'implémentation…)."
     tools: "<strong>Outils :</strong> Figma, FigJam, Notion, Miro, Mixpanel, Gsuite, Microsoft Office et leurs équivalents." 

   - subtitle: "Product Management"
     description: "Au même titre que le produit, l'expérience de travail doit être positive, efficace et satisfaisante pour tous les membres de l'équipe."
     items:
      - "<strong>🚀 Vision produit :</strong> définir et encadrer la vision produit, garantir l'adéquation du produit avec cette vision."
      - "<strong>🗓️ Roadmapping :</strong> intégrer les retours notamment utilisateurs, prioriser les développements, communiquer et planifier avec l'équipe."
      - "<strong>📝 Specs :</strong> spécifier des fonctionnalités ou corner cases."
      - "<strong>⚙️ Process :</strong> concevoir des process adaptés (workflow, rituels, outils…)."
     tools: "<strong>Outils :</strong> Notion, FigJam, Miro, Mixpanel, Trello, GitLab, JIRA et leurs équivalents."

   - subtitle: "DesignOps"
     description: "Evaluation et recommandations pour fluidifier les process et harmoniser la collaboration entre les équipes Design, Tech et Produit."
     items:
      - "<strong>👐 Workshop :</strong> intervention rapide et macro avec observations, rencontres avec les équipes, identification des pain points et proposition d'améliorations."
      - "<strong>🔎 Audit complet :</strong> intervention plus longue avec des rencontres en groupe et/ou des entretiens individuels, évaluation des process actuels et élaboration d'un workflow personnalisé suivi d'itérations avec les équipes."
   
   - subtitle: "Bon à savoir"
     description: "J'ai un <strong>excellent contact</strong> avec les équipes tech 🧑‍💻<br/>Je comprends bien les problèmatiques techniques pour trouver des compromis en bonne coopération. Merci à mes anciens collègues de m'avoir fait monter en compétences sur ces sujets !<br/><br/>Je ne fais pas de Direction Artistique ou UI Design 🎨<br/>L'esthétique d'un produit est tout aussi importante que son ergonomie. Ces 2 expertises sont complémentaires mais quasi impossibles à maîtriser profondément par une même personne. <br/>Si vous avez également ce besoin, je connais des personnes géniales avec qui j'ai l'habitude de <strong>travailler en binôme</strong> !<br/> Cela dit, je peux utiliser un Design System existant dans mes maquettes ou intervenir sur sa stratégie !"

#-------------------------------
# Offer

offre:
  title: "<span class=\"text-span\">Offre</span>"
  items:
   - subtitle: "Coup de pouce"
     target: "Adaptée aux petits budgets avec de l'ambition."
     description: "Des sessions de conseils d'1h (ou plus) à la demande pour repartir avec des pistes concrètes à appliquer tout de suite."
     example: "<strong>40%</strong> de mes client.es commencent par ce choix rapide, pratique et abordable."
   - subtitle: "Mission définie"
     target: "Répondre à un besoin précis avec un livrable concret et actionnable."
     description: "On identifie le besoin et sa réponse (audit, specs, recherche, ect.) adaptée à tes ressources et à ton timing."
     example: "<strong>40%</strong> de mes client.es optent pour ce format délimité et efficace."
   - subtitle: "Comme en interne"
     target: "L'accompagnement complet et flexible."
     description: "Je travaille au rythme de ton équipe (X jours / semaine) pour prioriser et avancer sur les sujets clés du projet."
     example: "<strong>20%</strong> de mes client.es préfèrent m'intégrer en tant qu'alliée du quotidien."
  description: "Contacte-moi pour discuter de tes enjeux  : produit / service, objectifs, cibles, roadmap, ressources, organisation...<br/>On trouvera la <strong>formule la plus adaptée</strong> pour répondre à tes besoins à hauteur de tes ressources et renforcer tes chances de succès !"

#-------------------------------
# Community section

community:
  title: "<span class=\"text-span\">Communautés</span>"
  items:
    - name: "Team for the Planet"
      description: "Team for the Planet rassemble de l'argent pour détecter et déployer 100 innovations mondiales contre les gaz à effet de serre."
      link: "https://team-planet.com/fr"
      logo: "/images/communities/team-planet.png"
    
    - name: "Climate House"
      description: "La Climate House est une maison qui rassemble des entrepreneurs, entreprises, investisseurs, associations, activistes, chercheurs, scientifiques, étudiants... Ces architectes de demain, quels que soient les freins auxquels ils sont confrontés — financement, visibilité, technologie ou réglementation — pourront, s'inspirer les uns les autres, et ensemble maximiser et accélérer leur impact."
      link: "https://climate.house/"
      logo: "/images/communities/climate-house.png"
    
    - name: "Freelance For Good"
      description: "Social Declik est un collectif d'indépendants qui proposent leurs compétences au service du bien commun pour aider des entreprises engagées à résoudre des problématiques environnementales ou sociétales."
      link: "https://socialdeclik.com/"
      logo: "/images/communities/social-declik.png"
    
    - name: "The Impact Circle"
      description: "The Impact Circle est une communauté qui facilite le partage de connaissances, élargit les réseaux et augmente notre impact collectif au sein de l'écosystème entrepreneurial à impact."
      link: "https://theimpactcircle.fr/"
      logo: "/images/communities/impact-circle.jpg"
   #- "<strong><a href='https://team-planet.com/fr' style='text-decoration: underline;'>L'Opservatoire :</strong> l'Harmonie 🕊"

#-------------------------------
# Mécenat section

mecenat:
  title: "<span class=\"text-span\">Mécénat de compétences</span>"
  items:
   - "<strong><a href='https://initiatives.theshifters.org/initiative/I20240714191246/' style='text-decoration: underline;' target='_blank'>Les Shifters</a> :</strong> Dans le cadre de la Grande Consultation du Sport, je suis volontaire pour conduire des entretiens qualitatifs avec des sportifs amateurs et rapporter leurs résultats."
   - "<strong><a href='https://www.innoverpourlatransitionecologique.fr/fr/challenges/open-booster' style='text-decoration: underline;' target='_blank'>Agence Française de Développement</a> :</strong> Dans le cadre du Challenge de l'Open Booster de l'Initiative Adapt'Action, j'ai été volontaire UX Designer et cheffe de projet pour Notre Logi'eau."
   - "<strong><a href='https://startupforkids.fr/programme-change-makher/' style='text-decoration: underline;' target='_blank'>Change Mak'Her</a> :</strong> mentor pour ce programme pour les jeunes filles de 13 à 18 ans : un accompagnement d'un an pour créer un projet numérique à impact !"
   #- "<strong><a href='https://team-planet.com/fr' style='text-decoration: underline;'>L'Opservatoire :</strong> l'Harmonie 🕊"
   - "N'hésitez pas à me contacter pour vous aider !"

#-------------------------------
# Projects Settings

#projects__settings:
#  projects__title: Latest <span class="text-span">Works</span> # Add a 'text-span' class to highlight text.
#  projects__description: I shows only the best websites and portfolios built completely with passion, simplicity & creativity!


#-------------------------------
# Testimonials Section

#testimonial__title: My Happy <span class="text-span">Clients</span> # Add a 'text-span' class to highlight text.

#testimonial-items:
#  - name: "Zaire Baptista"
#    image: "/images/client-1.jpg"
#    designation : "Traveler"
#    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."
#
#  - name: "Ann Philips"
#    image: "/images/client-2.jpg"
#    designation : "Designer"
#    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."
#
#  - name: "Roger Bergson"
#    image: "/images/client-3.jpg"
#    designation : "CEO, Founder"
#    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."
#
#  - name: "Julie Arnold"
#    image: "/images/client-4.jpg"
#    designation : "Full stack developer"
#    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."


#-------------------------------
# Blog Section

blog__settings:
  blog__title: Derniers <span class="text-span">partages</span> d'expérience # Add a 'text-span' class to highlight text.
  blog__description:


#-------------------------------
# Contact Settings

contact__settings:
  contact__email: your@email.com # Add your email for contact form
  contact__title: <span class="text-span">Get</span> in touch # Add a title to your form
  contact__description: Avenco comes with a built-in contact form. # Add a description to your form

# NOTE
# Avenco comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Newsletter Settings
# mailchimp__settings:
  #mailchimp__title: <span class="text-span">Join</span> my mailing list # Add your title
  #mailchimp__text: " 'Get inspiration, updates and', 'cool stuff about design!' " # Add descriptions to the form by wrapping the text in single quotes. If you want to use more than one sentence, be sure to separate them with a comma.
  #mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  #mailchimp__button__text: Subscribe # Add your button text


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Footer Settings
# Social Links
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/alexiabuclet/"}
- {icon: "ion-logo-instagram", link: "https://www.instagram.com/alexiabuclet/"}
- {icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 21 21" width="21" height="21"><path fill="currentColor" d="M13.54 12a6.8 6.8 0 01-6.77 6.82A6.8 6.8 0 010 12a6.8 6.8 0 016.77-6.82A6.8 6.8 0 0113.54 12zM20.96 12c0 3.54-1.51 6.42-3.38 6.42-1.87 0-3.39-2.88-3.39-6.42s1.52-6.42 3.39-6.42 3.38 2.88 3.38 6.42M24 12c0 3.17-.53 5.75-1.19 5.75-.66 0-1.19-2.58-1.19-5.75s.53-5.75 1.19-5.75C23.47 6.25 24 8.83 24 12z"/></svg>', link: "https://medium.com/@alexia.buclet"}
#- {icon: "ion-logo-twitter", link: "https://x.com/alexiabuclet"}
#- {icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="21" height="21"><path d="M0 4.48v15.04h24V4.48H0zM18 10.09c0 .85-.68 1.53-1.53 1.53H15.6v3.81h.77c.85 0 1.53.68 1.53 1.53s-.68 1.53-1.53 1.53H15.6v2.02h-2.02v-2.02h-1.53c-.85 0-1.53-.68-1.53-1.53s.68-1.53 1.53-1.53h1.53v-3.81h-1.53c-.85 0-1.53-.68-1.53-1.53s.68-1.53 1.53-1.53h1.53V6.5h2.02v3.59H18v1.53z"/></svg>', link: "https://www.behance.net/AlexiaBuclet"}
- {icon: "ion-logo-youtube", link: "https://www.youtube.com/@alexiabuclet"}
#- {icon: "ion-logo-github", link: "https://github.com"}
#- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
#- {icon: "ion-logo-codepen", link: "https://codepen.io"}
#- {icon: "ion-logo-vimeo", link: "https://vimeo.com"}

linkedin: https://www.linkedin.com/in/alexiabuclet/

